"""
Build database/seed_skills_library_v2.sql and nlp/resources/skills_taxonomy.json
from data/skills/skills_library.csv (the single source of truth).

Usage (from repo root):
    python data/skills/build_skills_seed.py

Exits with a non-zero code if the CSV fails validation.
"""

import json
import sys
from collections import Counter
from datetime import datetime

from skills_lib import CSV_PATH, REPO_ROOT, load_skills, load_v1_skill_names, validate

SEED_PATH = REPO_ROOT / "database" / "seed_skills_library_v2.sql"
TAXONOMY_PATH = REPO_ROOT / "nlp" / "resources" / "skills_taxonomy.json"


def q(s):
    return "'" + s.replace("'", "''") + "'"


def sql_array(items):
    return "ARRAY[" + ", ".join(q(a) for a in items) + "]::TEXT[]"


def build_sql(rows, generated_at):
    counts = Counter(r["category"] for r in rows)
    header = f"""-- ============================================================
-- SEAGAS — Skills Library v2
-- AUTO-GENERATED by data/skills/build_skills_seed.py — DO NOT EDIT BY HAND.
-- Edit data/skills/skills_library.csv, then run:
--     python data/skills/build_skills_seed.py
--     python -m pytest tests/test_skills_library.py -q
--     psql -U postgres -d seagas_db -f database/seed_skills_library_v2.sql
--
-- Total skills : {len(rows)}  ({", ".join(f"{c} {counts[c]}" for c in sorted(counts))})
-- Generated at : {generated_at}
--
-- Run AFTER schema.sql. Idempotent: ON CONFLICT (skill_name) DO UPDATE, so
-- alias / category / description fixes to the 32 v1 skills also take effect.
-- Any error aborts the whole transaction.
-- ============================================================

\\set ON_ERROR_STOP on

BEGIN;

INSERT INTO skills_library (skill_name, category, aliases, description) VALUES
"""
    values = []
    for r in rows:
        values.append(f"({q(r['skill_name'])}, {q(r['category'])}, {sql_array(r['aliases'])}, {q(r['description'])})")
    body = ",\n".join(values)
    footer = """
ON CONFLICT (skill_name) DO UPDATE SET
    category    = EXCLUDED.category,
    aliases     = EXCLUDED.aliases,
    description = EXCLUDED.description;

COMMIT;

-- ── VERIFY ───────────────────────────────────────────────────
SELECT category, COUNT(*) AS skill_count
FROM skills_library
WHERE is_active = TRUE
GROUP BY category
ORDER BY category;
"""
    return header + body + footer


def build_taxonomy(rows, generated_at):
    return {
        "generated_at": generated_at,
        "source": "data/skills/skills_library.csv",
        "skill_count": len(rows),
        "skills": [
            {
                "skill_name": r["skill_name"],
                "category": r["category"],
                "subcategory": r["subcategory"],
                "aliases": r["aliases"],
                "ambiguous_aliases": r["ambiguous_aliases"],
                "description": r["description"],
                "source": r["source"],
            }
            for r in rows
        ],
    }


def main():
    rows = load_skills()
    problems = validate(rows, load_v1_skill_names())
    if problems:
        print(f"Validation failed for {CSV_PATH}:", file=sys.stderr)
        for p in problems:
            print("  - " + p, file=sys.stderr)
        sys.exit(1)

    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M")
    SEED_PATH.write_text(build_sql(rows, generated_at), encoding="utf-8")
    TAXONOMY_PATH.parent.mkdir(parents=True, exist_ok=True)
    TAXONOMY_PATH.write_text(json.dumps(build_taxonomy(rows, generated_at), indent=2, ensure_ascii=False) + "\n",
                             encoding="utf-8")
    counts = Counter(r["category"] for r in rows)
    print(f"OK: {len(rows)} skills -> {SEED_PATH.relative_to(REPO_ROOT)}, {TAXONOMY_PATH.relative_to(REPO_ROOT)}")
    for c in sorted(counts):
        print(f"  {c:<12} {counts[c]}")


if __name__ == "__main__":
    main()
