-- SEAGAS: remove all synthetic students generated by generate_synthetic_data.py
-- ON DELETE CASCADE removes their profiles, skills, projects, certifications,
-- assessments and recommendations as well.
-- Usage: psql -U postgres -d seagas_db -f data/delete_synthetic_data.sql

DELETE FROM users WHERE email LIKE '%@synthetic.seagas.test';
